### Combining all "FBRef Matchday" seasonal datasets

In [1]:
import pandas as pd
import glob
import os
import numpy as np

# setting the path for joining multiple files
files = os.path.join("C:\\Users\\suwad\\OneDrive - Middlesex University\\Desktop\\MDX\Modules\\8. CST4444 Individual Project\\06. Rsearch Datasets\\Source\\1. FBRef\\3. Match Stats 2011-2022\\", "*.csv")

# list of merged files returned
files = glob.glob(files)

# joining files with concat and read_csv
pd.set_option('display.max_columns', None)
df = pd.concat(map(pd.read_csv, files), ignore_index=True)
df

,league,season,game,week,day,date,time,home_team,score,away_team,attendance,venue,referee,match_report,notes,game_id,home_xg,away_xg
0,ENG-Premier League,1112,2011-08-13 Blackburn-Wolves,1.0,Sat,2011-08-13,NaN,Blackburn,1–2,Wolves,NaN,NaN,Kevin Friend,/en/matches/f2922720/Blackburn-Rovers-Wolverha...,NaN,f2922720,NaN,NaN
1,ENG-Premier League,1112,2011-08-13 Fulham-Aston Villa,1.0,Sat,2011-08-13,NaN,Fulham,0–0,Aston Villa,NaN,NaN,Lee Mason,/en/matches/3f8d97c0/Fulham-Aston-Villa-August...,NaN,3f8d97c0,NaN,NaN
2,ENG-Premier League,1112,2011-08-13 Liverpool-Sunderland,1.0,Sat,2011-08-13,NaN,Liverpool,1–1,Sunderland,NaN,NaN,Phil Dowd,/en/matches/33de6206/Liverpool-Sunderland-Augu...,NaN,33de6206,NaN,NaN
3,ENG-Premier League,1112,2011-08-13 Newcastle Utd-Arsenal,1.0,Sat,2011-08-13,NaN,Newcastle Utd,0–0,Arsenal,NaN,NaN,Peter Walton,/en/matches/e0a75cb8/Newcastle-United-Arsenal-...,NaN,e0a75cb8,NaN,NaN
4,ENG-Premier League,1112,2011-08-13 QPR-Bolton,1.0,Sat,2011-08-13,NaN,QPR,0–4,Bolton,NaN,NaN,Martin Atkinson,/en/matches/251d86e5/Queens-Park-Rangers-Bolto...,NaN,251d86e5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4690,ENG-Premier League,2122,2022-05-22 Crystal Palace-Manchester Utd,38.0,Sun,2022-05-22,16:00,Crystal Palace,1–0,Manchester Utd,25434.0,Selhurst Park,Martin Atkinson,/en/matches/19173099/Crystal-Palace-Manchester...,NaN,19173099,0.5,0.8
4691,ENG-Premier League,2122,2022-05-22 Leicester City-Southampton,38.0,Sun,2022-05-22,16:00,Leicester City,4–1,Southampton,32003.0,King Power Stadium,Jonathan Moss,/en/matches/16e2761e/Leicester-City-Southampto...,NaN,16e2761e,2.3,1.2
4692,ENG-Premier League,2122,2022-05-22 Liverpool-Wolves,38.0,Sun,2022-05-22,16:00,Liverpool,3–1,Wolves,53097.0,Anfield,Anthony Taylor,/en/matches/8b0f3e28/Liverpool-Wolverhampton-W...,NaN,8b0f3e28,3.2,1.1
4693,ENG-Premier League,2122,2022-05-22 Manchester City-Aston Villa,38.0,Sun,2022-05-22,16:00,Manchester City,3–2,Aston Villa,53395.0,Etihad Stadium,Michael Oliver,/en/matches/7b4b63d0/Manchester-City-Aston-Vil...,NaN,7b4b63d0,2.9,0.3
4694,ENG-Premier League,2122,2022-05-22 Norwich City-Tottenham,38.0,Sun,2022-05-22,16:00,Norwich City,0–5,Tottenham,27022.0,Carrow Road,Chris Kavanagh,/en/matches/771ecae9/Norwich-City-Tottenham-Ho...,NaN,771ecae9,0.3,3.7

### Selecting useful metrics for future macth prediction
#### Appropriate match data

In [2]:
df.loc[df['season'] == 1112, 'season'] = 11
df.loc[df['season'] == 1213, 'season'] = 12
df.loc[df['season'] == 1314, 'season'] = 13
df.loc[df['season'] == 1415, 'season'] = 14
df.loc[df['season'] == 1516, 'season'] = 15
df.loc[df['season'] == 1617, 'season'] = 16
df.loc[df['season'] == 1718, 'season'] = 17
df.loc[df['season'] == 1819, 'season'] = 18
df.loc[df['season'] == 1920, 'season'] = 19
df.loc[df['season'] == 2021, 'season'] = 20
df.loc[df['season'] == 2122, 'season'] = 21

In [3]:
new_df = df.loc[:, df.columns.isin(['season', 'week', 'date', 'home_team', 'away_team', 'venue', 'referee', 'attendance', 'home_xg', 'away_xg'])]
new_df

,season,week,date,home_team,away_team,attendance,venue,referee,home_xg,away_xg
0,11,1.0,2011-08-13,Blackburn,Wolves,NaN,NaN,Kevin Friend,NaN,NaN
1,11,1.0,2011-08-13,Fulham,Aston Villa,NaN,NaN,Lee Mason,NaN,NaN
2,11,1.0,2011-08-13,Liverpool,Sunderland,NaN,NaN,Phil Dowd,NaN,NaN
3,11,1.0,2011-08-13,Newcastle Utd,Arsenal,NaN,NaN,Peter Walton,NaN,NaN
4,11,1.0,2011-08-13,QPR,Bolton,NaN,NaN,Martin Atkinson,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
4690,21,38.0,2022-05-22,Crystal Palace,Manchester Utd,25434.0,Selhurst Park,Martin Atkinson,0.5,0.8
4691,21,38.0,2022-05-22,Leicester City,Southampton,32003.0,King Power Stadium,Jonathan Moss,2.3,1.2
4692,21,38.0,2022-05-22,Liverpool,Wolves,53097.0,Anfield,Anthony Taylor,3.2,1.1
4693,21,38.0,2022-05-22,Manchester City,Aston Villa,53395.0,Etihad Stadium,Michael Oliver,2.9,0.3
4694,21,38.0,2022-05-22,Norwich City,Tottenham,27022.0,Carrow Road,Chris Kavanagh,0.3,3.7

### Storing the new Dataframe

In [4]:
new_df.to_csv(r'C:\Users\suwad\OneDrive - Middlesex University\Desktop\MDX\Modules\8. CST4444 Individual Project\06. Rsearch Datasets\Processed\FBRef.csv', sep=',', index=False, encoding='utf-8')